### PR TITLE
The bazel binaries are now put inside the user cache dir

### PR DESCRIPTION
**Pull request by mpassell**
Just a quick README fix that I happened to notice.

### CODE REVIEW

**Comment by jbduncan** [comment]
Wait, isn't this a bug? I ask because last time I used the Python version of Bazelisk, it stored the Bazel binaries in `.bazelisk`, so I'm a bit surprised that the Go version stores them in a different location. Should we not make the Python and Go versions consistent instead? 🤔

**Comment by mpassell** [comment]
You're right - https://github.com/philwo/bazelisk/blob/master/bazelisk.py#L256 . I've recently heard people advocating for the use of the user cache dir for cases like this, partly since it allows people to choose where the files go (at least on Linux) by setting `XDG_CACHE_HOME`.

**Comment by jbduncan** [comment]
Sounds good to me, although I do believe that an explicit goal of the Python version is to avoid using third-party modules so that the script can be used in a self-contained fashion. I could be wrong about this though. :)

@philwo Do you have any thoughts regarding all this?

**Comment by philwo** [comment]
I would prefer to change the Python version to use the same approach as Go:

> On Unix systems, it returns $XDG_CACHE_HOME as specified by https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html if non-empty, else $HOME/.cache. On Darwin, it returns $HOME/Library/Caches. On Windows, it returns %LocalAppData%. On Plan 9, it returns $home/lib/cache.

I think this is preferable to using the home directory of the user directly and also seems to give nice results on all supported platforms.

Let's not add a third-party dependency for this, though, due to the reason that @jbduncan mentioned. If someone wants to give this a try, I'm happy to review a PR. :)

**Comment by philwo** [comment]
@mpassell Thanks for the PR! I'm happy to merge this, but considering that the Python behavior still has a different behavior, should we either mention both, or wait until we implemented the same logic in the Python version?

**Comment by mpassell** [comment]
You're welcome. :) If the logic change in Python is as simple as I'm guessing, holding off on this until they're consistent makes sense. Oh, and fair enough about the module. It probably doesn't do much more than reading in a few env vars, anyway. I can try to take a crack at this tomorrow, but the result may not be very idiomatic, since I'm no Python expert.

**Comment by mpassell** [comment]
I'm getting back to this now. I guess I'll just port https://github.com/golang/go/blob/4b05dc91b0fe99724721e3545807f3b8f1310c52/src/os/file.go#L347 to the Python version for consistency. Does bazelisk support Windows or Plan9? (I'm guessing maybe on the former, unlikely on the latter. 😄 )

**Comment by philwo** [comment]
Thanks! Yes, Windows is supported, Plan9 not (yet?) 😄

The BAZELISK_HOME should still be supported - it's used in the interesting tests and maybe even on Bazel's CI to override the location.

**Comment by mpassell** [comment]
Let me know what you think of the code I pushed up. I'm actually going to repush it since it's using the wrong git identity for me, but the code won't change.

**Comment by philwo** [comment]
Thanks so much @mpassell! Looks great. :)

For the record, I verified that the Google CLA has been signed, so I can merge this PR.

**Comment by mpassell** [comment]
Great! Yup, I signed the CLA so that I could make a little doc fix to Skylib. So far, that PR hasn't ended up in my writing any code. 😆

**Pull request merged**
